---
title: "Capstone Project Proposal"
author: "Roberta Munive"
date: "April 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Abstract

This project will analyze risk factors, laboratory test results, clinical observations, and symptoms to predict chronic kidney disease in a patient.  Automated analysis of patient data could be implemented in a clinical decision support system to make the differential diagnosis process more efficient. 

##Problem Setup

This project will analyze risk factors, laboratory test results, clinical observations, and symptoms to predict chronic kidney disease in a patient. An automated analysis for predicting chronic kidney disease in a patient has the potential to (1) increase clinician and hospital efficiency and (2) improve patient outcomes.

In order to receive maximum reimbusement, hospitals must demonstrate efficiency and quality of care. Hospitals are evaluated based upon benchmark measures or comparisons to other hospitals.  One such example is the Medicare Spending Per Beneficiary (MSPB) Measure which is utilized by the Centers for Medicare and Medicaid Services (CMS). 

Chronic kidney disease is characterized by the gradual loss of kidney function over time.  In the early stages of the disease, the patient may experience few noticeable symptoms. The patient may be unaware that there is a problem until irreversible kidney damage has occurred.  Treatment involves slowing the progression of the disease.  Thus, it is crucial that a diagnosis be made as early as possible. Automating the analysis of laboratory tests and clinical indicators may speed the diagnosis process.  

The two primary causes of chronic kidney disease are diabetes and hypertension.  Thus, it is hypothesized that chronic kidney disease will be most strongly correlated with these two variables.  Other risk factors include age and cardiovascular disease.  Common signs and symptoms include loss of appetite, anemia, and pedal edema.  The analysis will examine these variables as well as the results of a variety of blood and urine laboratory tests that measure kidney function.

##Potential Clients

Clinicians, hospitals, and insurance companies are some of the clients that could benefit from the automated analysis of patient data to predict chronic kidney disease. 

The analysis approach developed for this project could be implemented in a clinical decision support system to automate the clinical diagnosis of chronic kidney disease or eliminate it as a possibility during the differential diagnosis process.  Increased efficiency of clinicians and hospital resources can improve delivery of care. 

The analysis approach could also be utilized by insurance companies to screen patients for chronic kidney disease.  Catching the disease during the early stages can potentially improve patient outcomes and reduce costs. 

##Data

A total of twenty-five attributes from four hundred patients will be examined.  Patient variables will be obtained from the Chronic Kidney Disease Data Set available [here](https://archive.ics.uci.edu/ml/datasets/chronic_kidney_disease).  

Patient attributes:

* Subject number
* Age (in years)
* Blood pressure (in mm/Hg)
* Urine tests
     + Specific gravity (1.005, 1.010, 1.015, 1.020, 1.025)
     + Albumin (0, 1, 2, 3, 4, 5)
     + Sugar (0, 1, 2, 3, 4, 5)
     + Red blood cells (normal, abnormal)
     + Pus cell (normal, abnormal)
     + Pus cell clumps (present, not present)
     + Bacteria (present, not present)
* Blood tests
     + Blood glucose random (in mgs/dl)
     + Blood urea (in mgs/dl)
     + Serum creatinine (in mgs/dl)
     + Sodium (in mEq/L)
     + Potassium (mEq/L)
     + Hemoglobin (in gms)
     + Packed cell volume
     + White blood cell count (in cells/cmm)
     + Red blood cell count (in millions/cmm)
* Hypertension (yes, no)
* Diabetes mellitus (yes, no)
* Coronary artery disease (yes, no)
* Appetite (good, poor)
* Pedal edema (yes, no)
* Anemia (yes, no)
* Whether nor not the patient has chronic kidney disease (ckd, notckd)


The dataset was donated on July 3, 2015 to the UCI Machine Learning Repository by Dr. P. Soundarapandian, a nephrologist at Apollo Hospital in India and L. Jerlin Rubini and Dr. P. Eswaran of Alagappa University in India.

##Analysis Approach

The analysis will use linear regression, logistic regression, and decision trees. 

The two primary causes of chronic kidney disease are diabetes and hypertension.  Thus, it is hypothesized that chronic kidney disease will be most strongly correlated with these two variables.  Patient attributes which are indicative of diabetes (e.g., blood glucose) and hypertension would also be expected to have a high correlation with chronic kidney disease. One challenge in analyzing the data will be the fact that the variables are not truly independent. Correlation between the attributes will need to be explored.  Further research into the laboratory tests will be conducted in order to ascertain which tests are typically ordered for chronic kidney disease, diabetes, and hypertension.  

In order to screen for kidney disease, the National Kidney Foundation recommends the following: 
* blood pressure measurement
* urine protein test (e.g., urine albumin)
* estimated glomerular filtration rate (e.g., blood creatinine test)

Elevated blood pressure and abnormal readings on the urine albumin and blood creatine rate should be highly correlated to chronic kidney disease.  

The test results will need to be grouped into values that are considered normal or abnormal.  Are the abnormal values too high or too low? What does it indicate when a particular value is too high or too low? 

Some additional tests to screen for kidney disease include blood urea and creatinine clearance. A urinalysis may be used as an additional screening for protein.  The urinalysis is not as sensitive as the albumin test for detecting kidney damage.  However, the urinalysis gives fewer false indicators of kidney damage.  The urinalysis also checks for the presence of red blood cells and white blood cells.  These blood cells are not normally present in urine and may be indicative of kidney disease.  


Not all test results or clinical observations were available for each patient. The analysis will need to take into account these missing values.

##Deliverables

Deliverables will include R code, a report, and a slide deck.  The code will execute the analysis and automatically predict whether or not the patient has chronic kidney disease.  The report and slide deck will describe the findings as well as the analysis process used to determine the findings.  The report and slide deck will attempt to persuade a fictitious hospital administrator to integrate the analysis approach into the clinical decision support system currently in use at the hospital.

##References

About chronic kidney disease. (2017, February 15).  Retrieved from https://www.kidney.org/atoz/content/about-chronic-kidney-disease.

Brinkman, S. and Zabel, E. (2017, August 22).  Medicare spending per beneficiary: Analyzing MSPB data to identify primary drivers.  Retrieved from https://www.lsqin.org/wp-content/uploads/2017/08/Medicare-Spending-per-Beneficiary-082217.pdf .

Chronic kidney disease. (2018, March 8).  Retrieved from https://www.mayoclinic.org/diseases-conditions/chronic-kidney-disease/symptoms-causes/syc-20354521.

Dua, D. and Karra Taniskidou, E. (2018).  UCI Machine Learning Repository http://archive.ics.uci.edu/ml.  Irvine, CA:  University of California, School of Information and Computer Science.

Kidney disease. (2018, January 5).  Retrieved from 
https://labtestsonline.org/conditions/kidney-disease

Lab tests online. (2018).  Retrieved from https://labtestsonline.org/

Spending per hospital patient with Medicare. (2012, July). Retrieved from https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-Instruments/hospital-value-based-purchasing/Downloads/MSPBDetail-July2012.pdf




